model:
  weights: "yolov5s"  # or path to custom trained weights
  confidence_threshold: 0.3
  image_size: 640

classes:
  names: ["bicycle", "car", "motorcycle", "airplane", "bus", "train", "truck", "boat"]
  colors: ["#FF6B6B", "#4ECDC4", "#45B7D1", "#96CEB4", "#FFEAA7", "#DDA0DD", "#98D8C8", "#F7DC6F"]

gui:
  title: "Vehicle Classifier"
  window_size: "800x900"
  max_image_size: [600, 500]

training:
  epochs: 100
  batch_size: 16
  image_size: 640 